task/urls.py
from django.urls import path

from .views import (
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TagListView,
    TagCreateView,
    task_status_update,
    TagUpdateView,
    TagDeleteView
)

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("task/create/", TaskCreateView.as_view(), name="task-create"),
    path("task/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("task/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("task/<int:pk>/update-status/", task_status_update, name="task-status-update"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tag/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tag/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
    path("tag/create/", TagCreateView.as_view(), name="tag-create"),
]

app_name = "task"

to_do_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("task.urls", namespace="task"))
]# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

task/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=63)

    def __str__(self) -> str:
        return self.name


class Task(models.Model):
    content = models.CharField(max_length=127)
    datetime = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(blank=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks")

    def __str__(self) -> str:
        return f"{self.content}, {self.deadline} (done={self.is_done})"

task/forms.py
from django import forms


from task.models import Task, Tag


class DateTimeInput(forms.DateTimeInput):
    input_type = "datetime"


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple(
            attrs={"class": "form-control"}
        )
    )

    class Meta:
        model = Task
        fields = ["content", "deadline", "tags"]
        widgets = {
            "content": forms.TextInput(
                attrs={"class": "form-control",
                       "placeholder": " Enter task content"}
            ),
            "deadline": forms.DateTimeInput(
                attrs={"type": "datetime-local",
                       "class": "form-control"}
            )
        }


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = "__all__"

task/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic

from task.models import Task, Tag
from task.forms import TaskForm, TagForm


class TaskListView(generic.ListView):
    model = Task


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("task:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("task:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("task:task-list")


class TagListView(generic.ListView):
    model = Tag


class TagCreateView(generic.CreateView):
    model = Tag
    form_class = TagForm
    success_url = reverse_lazy("task:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    form_class = TagForm
    success_url = reverse_lazy("task:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("task:tag-list")


def task_status_update(request, pk):
    task = Task.objects.get(id=pk)
    if task.is_done:
        task.is_done = False
        task.save()
    else:
        task.is_done = True
        task.save()
    return redirect("task:task-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>To-do</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
</head>

<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">

      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}

    </div>
    <div class="col-sm-7 ">

      {% block content %}{% endblock %}

    </div>
  </div>
</div>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group mt-3">
  <li class="list-group-item"><a href="{% url "task:task-list" %}">Home</a></li>
  <li class="list-group-item"><a href="{% url "task:tag-list" %}">Tags</a></li>
</ul>

templates/task/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <a  href="{% url "task:tag-list" %}" class="btn btn-secondary">Cancel</a>
    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/task/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Tag</h1>
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/task/tag_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Tags List
    <a href="{% url "task:tag-create" %}" class="btn btn-primary link-to-page">
      Create
    </a>
  </h1>
  <br>
  {% if tag_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for tag in tag_list %}
        <tr>
          <td>
            {{ tag.name }}
          </td>
          <td>
            <a href="{% url "task:tag-update" pk=tag.id %}">
              Update
            </a>
          </td>
          <td>
            <a style="color: red"
               href="{% url "task:tag-delete" pk=tag.id %}">
              Delete
            </a>
          </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
    <p>There are no tags right now</p>
  {% endif %}
{% endblock %}

templates/task/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <a  href="{% url "task:task-list" %}" class="btn btn-secondary">Cancel</a>
    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/task/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Task</h1>
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/task/task_list.html
{% extends "base.html" %}
{% load app_tags %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-6 text-left">
        <h1>TODO List</h1>
      </div>
      <div class="col-md-6 text-right mt-3">
        <a href="{% url "task:task-create" %}" class="btn btn-primary link-to-page">Create task</a>
      </div>
    </div>
  </div>
  <br>
  {% if task_list %}
    {% for task in task_list %}
      <div class="d-flex justify-content-between">
        <h4>
          <strong>{{ task.content }}</strong>
          <span
              class="{% if task.is_done %}text-success{% else %}text-danger{% endif %} mx-0">
                {% if task.is_done %}Done{% else %}Not done{% endif %}
          </span>
        </h4>

        <a href="{% url 'task:task-status-update' pk=task.id %}"
           class="btn {% if task.is_done %}btn-secondary{% else %}btn-success{% endif %} ms-2">
          {% if task.is_done %}Undo{% else %}Complete{% endif %}
        </a>
      </div>



      {% if task.deadline|get_remain_time %}
        <h5>Time remains: {{ task.deadline|get_remain_time }}</h5>
      {% else %}
        <h5>No time remains</h5>
      {% endif %}
      <p>Tags: {% for tag in task.tags.all %}{{ tag }}, {% endfor %}</p>
      <a href="{% url "task:task-update" pk=task.id %}">Update</a>
      <a href="{% url "task:task-delete" pk=task.id %}">Delete</a>
      <hr>
    {% endfor %}

  {% else %}
    <p>There is no tasks right now</p>
  {% endif %}
{% endblock %}